#!/bin/sh
if [ "${1:-}" = "--version" ]; then
  printf '%s\n' 'mq fake-1.0'
  exit 0
fi

[ "$2" = ".tree" ]
grep -Eq '^#{1,6}[[:space:]]' "$1"
[ "${MQ_FORCE_FAILURE:-0}" = 0 ] || exit 1
if [ -n "${MQ_TEST_LOG:-}" ]; then
  printf '%s|%s\n' "$1" "$2" >>"$MQ_TEST_LOG"
fi
