(install
 (section bin)
 (files
  (searxng-search as sandwalk-search-searxng)
  (searxng-service as sandwalk-searxng-service)
  (ddgr-search as sandwalk-search-ddgr)
  (ugrep-search as sandwalk-search-ugrep)
  (texiq-search as sandwalk-search-texiq)
  (qmd-search as sandwalk-search-qmd)
  (qmd-index as sandwalk-index-qmd)
  (web-fetch as sandwalk-fetch-web)
  (curl-pandoc-fetch as sandwalk-fetch-curl-pandoc)
  (playwright-fetch as sandwalk-fetch-playwright)
  (playwright-render as sandwalk-playwright-render)
  (arxiv-html-filter.lua as sandwalk-arxiv-html-filter.lua)
  (file-fetch as sandwalk-fetch-file)
  (docling-fetch as sandwalk-fetch-docling)
  (docling-normalize as sandwalk-docling-normalize)
  (youtube-fetch as sandwalk-fetch-youtube)
  (youtube-normalize as sandwalk-youtube-normalize)
  (texiq-fetch as sandwalk-fetch-texiq)
  (qmd-fetch as sandwalk-fetch-qmd)
  (xberg-fetch as sandwalk-fetch-xberg)
  (pandoc-pdf-export as sandwalk-export-pandoc-pdf)))
